language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chuckmdonaldson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chuckmdonaldson/react-test npm test

after_success:
  - docker build -t chuckmdonaldson/multi-client ./client
  - docker build -t chuckmdonaldson/multi-nginx ./nginx
  - docker build -t chuckmdonaldson/multi-server ./server
  - docker build -t chuckmdonaldson/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chuckmdonaldson/multi-client
  - docker push chuckmdonaldson/multi-nginx
  - docker push chuckmdonaldson/multi-server
  - docker push chuckmdonaldson/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-681603655492'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY