version: '3'
services:
  server:
    image: chuckmdonaldson/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASWORD
      - PGPOR=$PGPORT
  nginx:
    image: chuckmdonaldson/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  client:
    image: chuckmdonaldson/multi-client
    mem_limit: 128m
    hostname: client
  worker:
    image: chuckmdonaldson/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
